AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Template used for building AUR packages and adding them to a custom S3-based repository.

Parameters:
  PersonalRepository:
    Type: String
  PackageTable:
    Type: String
    Default: package-list
  FanoutStatusTable:
    Type: String
    Default: fanout-status
  RepositoryCountries:
    Type: String
    Default: "IE,GB"
  GithubWebhookSecret:
    Type: String
    Default: ABCD1234

Globals:
  Function:
    Timeout: 3
    Runtime: python3.7
    Environment:
      Variables:
        PACKAGE_TABLE:
          Ref: PackageData

Resources:

  #####
  # Functions
  ###
  PackageUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: package-update
      Description: Scheduled updating of the package list in all repositories
      CodeUri: package_updater
      Handler: update_packages.lambda_handler
      Timeout: 600
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PackageData
      Environment:
        Variables:
          COUNTRIES: !Ref RepositoryCountries
          PERSONAL_REPO: !Ref PersonalRepository
          PACKAGE_TABLE: !Ref PackageTable
      Events:
        PackageUpdateSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(6 hours)

  PkgbuildRetrieverFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pkgbuild-retriever
      Description: API for pulling the PKGBUILD from Github
      CodeUri: pkgbuild_retriever
      Handler: retrieve_pkgbuild.lambda_handler
      Policies:
        ###
      Environment:
        Variables:
          NEXT_FUNC: !GetAtt PkgbuildParserFunction.Arn
          GITHUB_WEBHOOK_SECRET: !Ref GithubWebhookSecret
      Events:
        RetrievePkgbuild:
          Type: Api
          Properties:
            Path: /update
            Method: post
      Layers:
        - !Ref AwsLayer

  PkgbuildParserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pkgbuild-parser
      Description: Parses the PKGBUILD and extracts a list of packages from it
      CodeUri: pkgbuild_parser
      Handler: parse_pkgbuild.lambda_handler
      #Policies:
      ###
      Environment:
        Variables:
          NEXT_FUNC: !GetAtt PkgbuildFanoutStarterFunction

  PkgbuildFanoutStarterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pkgbuild-fanout-starter
      Description: A starter function to set up the fan-out and fan-in of building packages
      CodeUri: pkgbuild_fanout_starter
      Handler: fanout.lambda_handler

  #####
  # Layers
  ###
  AwsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aws-dependencies
      Description: Dependencies for PKGBUILD apps
      ContentUri: src/
      CompatibleRuntimes:
        - python3.7
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

  #####
  # Database Tables
  ###
  PackageData:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Ref PackageTable
      PrimaryKey:
        Name: PackageName
        Type: String

  FanoutStatus:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref FanoutStatusTable
      AttributeDefinitions:
        - AttributeName: PackageName
          AttributeType: S
        - AttributeName: Status
          AttributeType: S
      KeySchema:
        - AttributeName: PackageName
          KeyType: HASH
        - AttributeName: Status
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3

#  HelloWorldFunction:
#    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#    Properties:
#      CodeUri: src/
#      Handler: app.lambda_handler
#      Runtime: python3.7
#      Events:
#        HelloWorld:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            Path: /hello
#            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  HelloWorldApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  PackageUpdateFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PackageUpdateFunction.Arn
  PackageUpdateFunctionIamRole:
    Description: "Implicit IAM Role created for Package Update function"
    Value: !GetAtt PackageUpdateFunctionRole.Arn
