AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Template used for building AUR packages and adding them to a custom S3-based repository.

Parameters:
  PersonalRepository:
    Type: String
  PackageTable:
    Type: String
    Default: package-list
  FanoutStatusTable:
    Type: String
    Default: fanout-status
  RepositoryCountries:
    Type: String
    Default: "IE,GB"
  GithubWebhookSecret:
    Type: String
    Default: ABCD1234
  ECSCluster:
    Type: String
    Default: "aur-pkgbuild-cluster"
  TaskDefinition:
    Type: String
    Default: "aur-pkgbuild-task"

Globals:
  Function:
    Timeout: 3
    Runtime: python3.7
    Environment:
      Variables:
        PACKAGE_TABLE:
          Ref: PackageData

Resources:

  #####
  # Functions
  ###
  PackageUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: package-update
      Description: Scheduled updating of the package list in all repositories
      Runtime: python3.7
      CodeUri: package_updater
      Handler: update_packages.lambda_handler
      Timeout: 600
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PackageData
      Environment:
        Variables:
          COUNTRIES: !Ref RepositoryCountries
          PERSONAL_REPO: !Ref PersonalRepository
          PACKAGE_TABLE: !Ref PackageTable
      Events:
        PackageUpdateSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(6 hours)

  PkgbuildRetrieverFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pkgbuild-retriever
      Description: API for pulling the PKGBUILD from Github
      Runtime: python3.7
      CodeUri: pkgbuild_retriever
      Handler: retrieve_pkgbuild.lambda_handler
      Policies:
        ###
      Environment:
        Variables:
          NEXT_FUNC: !GetAtt PkgbuildParserFunction.Arn
          GITHUB_WEBHOOK_SECRET: !Ref GithubWebhookSecret
      Events:
        RetrievePkgbuild:
          Type: Api
          Properties:
            Path: /update
            Method: post
      Layers:
        - !Ref AwsLayer

  PkgbuildParserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pkgbuild-parser
      Description: Parses the PKGBUILD and extracts a list of packages from it
      Runtime: python3.7
      CodeUri: pkgbuild_parser
      Handler: parse_pkgbuild.lambda_handler
      #Policies:
      ###
      Environment:
        Variables:
          NEXT_FUNC: !GetAtt PkgbuildFanoutStarterFunction.Arn
      Layers:
        - !Ref AwsLayer

  PkgbuildFanoutStarterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pkgbuild-fanout-starter
      Description: A starter function to set up the fan-out and fan-in of building packages
      Runtime: python3.7
      CodeUri: fanout_starter
      Handler: starter.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FanoutStatusTable
      Environment:
        Variables:
          FANOUT_STATUS: !Ref FanoutStatusTable
          FANOUT_QUEUE: !GetAtt FanoutQueue.Arn

  CheckPackageBuildFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: check-package-build
      Description: Checks each package on the queue and decides whether to build or ignore it
      Runtime: python3.7
      CodeUri: check_package_build
      Handler: check_package.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PackageData
      Environment:
        Variables:
          FANOUT_CONTROLLER: !GetAtt FanoutControllerFunction.Arn
          PACKAGE_TABLE: !Ref PackageTable
          PERSONAL_REPO: !Ref PersonalRepository
          BUILD_FUNC: !GetAtt BuildFunction.Arn
      Events:
        Type: SQS
        Properties:
          Queue: !GetAtt FanoutQueue.Arn

  BuildFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: build-package
      Description: Starts an ECS task to build a package and adds the package to the build queue
      Runtime: python3.7
      CodeUri: build_package
      Handler: build.lambda_handler
      Environment:
        Variables:
          BUILD_QUEUE: !GetAtt BuildQueue.Arn
          ECS_CLUSTER: !Ref ECSCluster
          TASK_DEFN: !Ref TaskDefinition

  FanoutControllerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fanout-controller
      Description: Manages the parallel building of packages via the FanoutStatus table
      Runtime: python3.7
      CodeUri: fanout_controller
      Handler: controller.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FanoutStatusTable
      Environment:
        Variables:
          FANOUT_STATUS: !Ref FanoutStatus
          METAPACKAGE_BUILDER: !GetAtt MetapackageBuilderFunction.Arn

  MetapackageBuilderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: metapackage-builder
      Description: Retrieves the metapackage PKGBUILD and queues it for building
      Runtime: python3.7
      CodeUri: metapackage_builder
      Handler: metapackage.lambda_handler
      Policies:
        ###
      Environment:
        Variables:
          BUILD_FUNC: !GetAtt BuildFunction.Arn
          PERSONAL_REPO: !Ref PersonalRepository

  #####
  # Layers
  ###
  AwsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aws-dependencies
      Description: Dependencies for PKGBUILD apps
      ContentUri: src/
      CompatibleRuntimes:
        - python3.7
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

  #####
  # Queue's
  ###
  FanoutQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "fanout-queue"

  BuildQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "aur-pkg-build"
      VisibilityTimeout: 600

  #####
  # ECS
  ###
  PkgbuildCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ECSCluster

  PkgbuildTaskDefinition:
    Type: AWS::ECS::TaskDefinition"
    Properties:
      Family: !Ref TaskDefinition
      Cpu: "4096"
      Memory: "8192"
      NetworkMode: "awsvpc"
      RequiresCompatibilities:
        - "FARGATE"
      TaskRoleArn: !GetAtt ### ROLE ARN
      ExecutionRoleArn: !GetAtt ### ROLE ARN
      ContainerDefinitions:
        - Name: "aur-pkg-build"
          Image: "couldinho/aur-pkg-build:latest"
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: "/ecs/aur-pkg-build"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: "ecs"
          Environment:
            - Name: "PUSHOVER_TOKEN"
              Value: ${ssm:pushoverToken}
            - Name: "PUSHOVER_USER"
              Value: ${ssm:pushoverUser}
            - Name: "REPO_NAME"
              Value: ${env:REPO_NAME}
            - Name: "REPO_ARCH"
              Value: ${env:REPO_ARCH}
            - Name: "REPO_URL"
              Value: ${env:REPO_URL}
            - Name: "AWS_REGION"
              Value:
                Ref: 'AWS::Region'
            - Name: "SQS_QUEUE_URL"
              Value: !Ref BuildQueue

  #####
  # Database Tables
  ###
  PackageData:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Ref PackageTable
      PrimaryKey:
        Name: PackageName
        Type: String

  FanoutStatus:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref FanoutStatusTable
      AttributeDefinitions:
        - AttributeName: PackageName
          AttributeType: S
        - AttributeName: Status
          AttributeType: S
      KeySchema:
        - AttributeName: PackageName
          KeyType: HASH
        - AttributeName: Status
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3

#  HelloWorldFunction:
#    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#    Properties:
#      CodeUri: src/
#      Handler: app.lambda_handler
#      Runtime: python3.7
#      Events:
#        HelloWorld:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            Path: /hello
#            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  HelloWorldApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  PackageUpdateFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PackageUpdateFunction.Arn
  PackageUpdateFunctionIamRole:
    Description: "Implicit IAM Role created for Package Update function"
    Value: !GetAtt PackageUpdateFunctionRole.Arn
